### ISSUE TITLE
Space in file extension

### ISSUE THREAD

**Issue by halilim** [grumpydev/Sublime-Notepad-Replacement#2]
To reproduce:
1. Install ST2, and this launcher etc
2. Double-click a file whose extension is not associated with a default app, e.g. something.py
3. Choose program from installed programs
4. Choose Notepad

What happens:
Syntax: Plain Text
F2 (Rename) -> there is a space in the end, i.e. `"something.py "` (note the space after .py part)

Expected result:
Syntax: Python
Rename -> no space in the end

The test to see that there is no space in the extension:
Right click on something.py and select "Open with Sublime Text 2" -> expected result

I suspected that SublimeLauncher.exe could be adding a space to the path, e.g. `"%1 "`. But I'm not sure since the source code is unavailable.

**Comment by grumpydev** [comment]
Umm, the source code is in the repo :-)

**Comment by halilim** [comment]
Sorry, probably I've been looking at the wrong place all the time :)

BTW, could you reproduce the issue?

**Comment by grumpydev** [comment]
I haven't used Sublime for a while now so I haven't replicated it - it's quite possible it's a bug, I did write it in about 10minutes :-)

**Comment by halilim** [comment]
Trying to reproduce it using JScript I think I've spotted the problem: [line 34 of SublimeLauncher.cpp](https://github.com/grumpydev/Sublime-Notepad-Replacement/blob/18e8acd6bc21b7aee2a288291f65ed28b44c5ae8/src/Sublime%20Launcher/SublimeLauncher/SublimeLauncher.cpp#L34) adds a redundant space after the path in the last iteration, and Sublime Text thinks it's a part of the file name.

**Comment by grumpydev** [comment]
Fixed
